# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Steven Gubkin
url:              https://stevengubkin.github.io/

author:            
  name:           'Steven Gubkin'

paginate:         5
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

sidebar_home_link:  true
